name: Release

on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set VERSION variable from tag
        run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
      - name: Set VERSION_NUMBER
        run: echo "VERSION_NUMBER=$(echo $VERSION | grep -i -P -o '^\d+\.\d+\.\d+')" >> $GITHUB_ENV
      - name: Build and Package
        run: dotnet pack ./ShippedItemInstancePlugin/ShippedItemInstancePlugin.csproj -c Release -o ./dist -p:NuspecFile=../AgGatewayShippedItemInstancePlugin.nuspec -p:NuspecProperties=version=${{ env.VERSION }} -p:FileVersion=${{ env.VERSION_NUMBER }}+${{ github.run_number }}
      - name: Push release to Github
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./dist/AgGatewayShippedItemInstancePlugin.${{ env.VERSION }}.nupkg
          tag: ${{ github.ref }}
      - name: Push release to public Nuget
        run: dotnet nuget push ./dist/AgGatewayShippedItemInstancePlugin.${{ env.VERSION }}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${NUGET_API_KEY}
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}